TRAIN_DATA = [
    ("It was Quirrell.", 
     {"entities": [(7, 15, "PERSONAJE")]}),
    ("“Severus?” Quirrell laughed, and it wasn’t his usual quivering treble, either, but cold and sharp.", 
     {"entities": [(1, 8, "PERSONAJE"), (11, 19, "PERSONAJE")]}),
    ("Your friend Miss Granger accidentally knocked me over as she rushed to set fire to Snape at that Quidditch match.", 
     {"entities": [(12, 24, "PERSONAJE"), (79, 84, "PERSONAJE"), (92, 101, "OBJETO_MAGICO")]}),
    ("I couldn’t do anything with Dumbledore watching.", 
     {"entities": [(28, 38, "PERSONAJE")]}),
    ("“You let the troll in?”", 
     {"entities": [(12, 17, "PERSONAJE")]}),
    ("It was only then that Harry realized what was standing behind Quirrell. It was the Mirror of Erised.", 
     {"entities": [(23, 28, "PERSONAJE"), (64, 72, "PERSONAJE"), (82, 98, "OBJETO_MAGICO")]}),
    ("He suspected me all along. Tried to frighten me — as though he could, when I had Lord Voldemort on my side….",
     {"entities": [(86, 100, "PERSONAJE")]}),
    ("He was at Hogwarts with your father, didn’t you know?",
     {"entities": [(11, 19, "LUGAR")]}),
    ("When I failed to steal the stone from Gringotts, he was most displeased.",
     {"entities": [(39, 48, "LUGAR")]}),
    ("He’d seen Quirrell there that very day, shaken hands with him in the Leaky Cauldron.",
     {"entities": [(11, 19, "PERSONAJE"), (68, 84, "LUGAR")]}),
    ("And to Harry’s horror, a voice answered, and the voice seemed to come from Quirrell himself.",
     {"entities": [(10, 15, "PERSONAJE"), (76, 84, "PERSONAJE")]}),
    ("“Yes — Potter — come here.”",
     {"entities": [(6, 12, "PERSONAJE")]}),
    ("It put its hand into its pocket and pulled out a blood-red stone.",
     {"entities": [(55, 60, "OBJETO_MAGICO")]}),
    ("As Harry moved aside, he felt the Sorcerer’s Stone against his leg.",
     {"entities": [(3, 8, "PERSONAJE"), (33, 50, "OBJETO_MAGICO")]}),
    ("Petrified, he watched as Quirrell reached up and began to unwrap his turban.",
     {"entities": [(28, 36, "PERSONAJE"), (66, 72, "OBJETO_MAGICO")]}),
    ("Where there should have been a back to Quirrell’s head, there was a face, the most terrible face Harry had ever seen.",
     {"entities": [(41, 49, "PERSONAJE"), (94, 99, "PERSONAJE")]}),
    ("Unicorn blood has strengthened me, these past weeks…you saw faithful Quirrell drinking it for me in the forest…",
     {"entities": [(0, 13, "OBJETO_MAGICO"), (68, 76, "PERSONAJE")]}),
    ("The smiling face of Albus Dumbledore swam into view above him.",
     {"entities": [(19, 35, "PERSONAJE")]}),
    ("Harry, please relax, or Madam Pomfrey will have me thrown out.",
     {"entities": [(0, 5, "PERSONAJE"), (26, 39, "PERSONAJE")]}),
    ("I believe your friends Misters Fred and George Weasley were responsible for trying to send you a toilet seat.",
     {"entities": [(30, 34, "PERSONAJE"), (39, 53, "PERSONAJE")]}),
    ("Mr. Ronald Weasley and Miss Granger will be most relieved you have come round, they have been extremely worried.",
     {"entities": [(4, 19, "PERSONAJE"), (24, 36, "PERSONAJE")]}),
    ("Not the Stone, boy, you — the effort involved nearly killed you.",
     {"entities": [(8, 13, "OBJETO_MAGICO")]}),
    ("Well, Nicolas and I have had a little chat, and agreed it’s all for the best.",
     {"entities": [(6, 13, "PERSONAJE")]}),
    ("To one as young as you, I’m sure it seems incredible, but to Nicolas and Perenelle, it really is like going to bed after a very, very long day.",
     {"entities": [(66, 73, "PERSONAJE"), (78, 87, "PERSONAJE")]}),
    ("Ah! Bettie Bott’s Every Flavor Beans!",
     {"entities": [(4, 38, "OBJETO_MAGICO")]}),
    ("And she let Ron and Hermione in.",
     {"entities": [(13, 16, "PERSONAJE"), (21, 29, "PERSONAJE")]}),
    ("“I always said he was off his rocker,” said Ron, looking quite impressed at how crazy his hero was.",
     {"entities": [(43, 46, "PERSONAJE")]}),
    ("Hagrid sidled through the door as he spoke.",
     {"entities": [(0, 6, "PERSONAJE")]}),
    ("Have a Chocolate Frog, I’ve got loads.…",
     {"entities": [(7, 22, "OBJETO_MAGICO")]}),
    ("He slipped into a seat between Ron and Hermione at the Gryffindor table and tried to ignore the fact that people were standing up to look at him.",
     {"entities": [(32, 35, "PERSONAJE"), (40, 48, "PERSONAJE"), (56, 66, "CASA_HOGWARTS")]}),
    ("A storm of cheering and stamping broke out from the Slytherin table.",
     {"entities": [(51, 60, "CASA_HOGWARTS")]}),
    ("Harry could see Draco Malfoy banging his goblet on the table.",
     {"entities": [(0, 5, "PERSONAJE"), (16, 28, "PERSONAJE")]}),
    ("First — to Mr. Ronald Weasley…",
     {"entities": [(13, 28, "PERSONAJE")]}),
    ("Second — to Miss Hermione Granger…for the use of cool logic in the face of fire, I award Gryffindor house fifty points.",
     {"entities": [(13, 30, "PERSONAJE"), (91, 101, "CASA_HOGWARTS")]}),
    ("I therefore award ten points to Mr. Neville Longbottom.",
     {"entities": [(33, 52, "PERSONAJE")]}),
    ("Snape was shaking Professor McGonagall’s hand, with a horrible, forced smile.",
     {"entities": [(0, 5, "PERSONAJE"), (20, 40, "PERSONAJE")]}),
    ("Even Neville scraped through, his good Herbology mark making up for his abysmal Potions one.",
     {"entities": [(5, 12, "PERSONAJE"), (76, 83, "OBJETO_MAGICO")]}),
    ("...they were boarding the Hogwarts Express; talking and laughing as the countryside became greener and tidier...",
     {"entities": [(25, 42, "LUGAR")]}),
    ("pulling into platform nine and three-quarters at King’s Cross Station.",
     {"entities": [(13, 44, "LUGAR"), (48, 68, "LUGAR")]}),
    ("It was Ginny Weasley, Ron’s younger sister, but she wasn’t pointing at Ron.",
     {"entities": [(7, 20, "PERSONAJE"), (22, 25, "PERSONAJE"), (69, 72, "PERSONAJE")]}),
    ("Behind him stood Aunt Petunia and Dudley, looking terrified at the very sight of Harry.",
     {"entities": [(18, 30, "PERSONAJE"), (35, 41, "PERSONAJE"), (78, 83, "PERSONAJE")]}),
    ("Could the basilisk be lurking in a shadowy corner, behind a pillar?",
     {"entities": [(10, 18, "PERSONAJE")]}),
    ("And where was Ginny?",
     {"entities": [(15, 20, "PERSONAJE")]}),
    ("He pulled out his wand and moved forward between the serpentine columns.",
     {"entities": [(18, 22, "OBJETO_MAGICO")]}),
    ("“Tom — Tom Riddle?”",
     {"entities": [(7, 18, "PERSONAJE")]}),
    ("“A memory,” said Riddle quietly. “Preserved in a diary for fifty years.”",
     {"entities": [(18, 24, "PERSONAJE"), (49, 54, "OBJETO_MAGICO")]}),
    ("“You’ve got to help me, Tom,” Harry said, raising Ginny’s head again.",
     {"entities": [(25, 28, "PERSONAJE"), (31, 36, "PERSONAJE"), (49, 54, "PERSONAJE")]}),
    ("Riddle’s smile broadened.",
     {"entities": [(0, 6, "PERSONAJE")]}),
    ("We’re in the Chamber of Secrets.",
     {"entities": [(11, 30, "LUGAR")]}),
    ("The diary,” said Riddle. `My diary. Little Ginny’s been writing in it for months and months...",
     {"entities": [(0, 10, "OBJETO_MAGICO"), (19, 25, "PERSONAJE"), (32, 37, "OBJETO_MAGICO"), (45, 50, "PERSONAJE")]}),
    ("She set the Serpent of Slytherin on four Mudbloods, and the Squib’s cat.",
     {"entities": [(12, 33, "PERSONAJE")]}),
    ("Only the Transfiguration teacher, Dumbledore, seemed to think Hagrid was innocent.",
     {"entities": [(32, 42, "PERSONAJE"), (63, 69, "PERSONAJE")]}),
    ("In a few hours the Mandrake Draught will be ready and everyone who was Petrified will be all right again —”",
     {"entities": [(19, 35, "OBJETO_MAGICO")]}),
    ("“Voldemort,” said Riddle softly, “is my past, present, and future, Harry Potter…”",
     {"entities": [(1, 10, "PERSONAJE"), (19, 25, "PERSONAJE"), (66, 78, "PERSONAJE")]}),
    ("Then he waved the wand once, and the letters of his name rearranged themselves: I AM LORD VOLDEMORT",
     {"entities": [(16, 20, "OBJETO_MAGICO"), (85, 102, "PERSONAJE")]}),
    ("“That’s a phoenix.” said Riddle, staring shrewdly back at it.",
     {"entities": [(10, 17, "PERSONAJE"), (25, 31, "PERSONAJE")]}),
    ("“Fawkes?” Harry breathed, and he felt the bird’s golden claws squeeze his shoulder gently.",
     {"entities": [(1, 7, "PERSONAJE"), (10, 15, "PERSONAJE")]}),
    ("...that’s the old school Sorting Hat —”",
     {"entities": [(26, 37, "OBJETO_MAGICO")]}),
    ("A gleaming silver sword had appeared inside the hat, its handle glittering with rubies the size of eggs.",
     {"entities": [(11, 23, "OBJETO_MAGICO")]}),
    ("But as warm blood drenched Harry’s arms, he felt a searing pain just above his elbow.",
     {"entities": [(28, 33, "PERSONAJE")]}),
    ("“Phoenix tears…” said Riddle quietly, staring at Harry’s arm.",
     {"entities": [(1, 14, "OBJETO_MAGICO"), (23, 29, "PERSONAJE"), (50, 55, "PERSONAJE")]}),
    ("For a split second, both Harry and Riddle, wand still raised, stared at it.",
     {"entities": [(27, 32, "PERSONAJE"), (37, 43, "PERSONAJE"), (45, 49, "OBJETO_MAGICO")]}),
    ("I’m going to be expelled!” Ginny wept as Harry helped her awkwardly to her feet.",
     {"entities": [(28, 33, "PERSONAJE"), (42, 47, "PERSONAJE")]}),
    ("Fawkes was waiting for them, hovering in the Chamber entrance.",
     {"entities": [(0, 6, "PERSONAJE")]}),
    ("“He’s Dumbledore’s,” said Harry, squeezing through himself.",
     {"entities": [(5, 15, "PERSONAJE"), (24, 29, "PERSONAJE")]}),
    ("His memory’s gone,” said Ron. “The Memory Charm backfired.",
     {"entities": [(27, 30, "PERSONAJE"), (38, 51, "HECHIZO")]}),
    ("...were hitting the wet floor of Moaning Myrtle’s bathroom...",
     {"entities": [(32, 56, "LUGAR")]}),
     ("‘Thank you, Minister.’", 
     {"entities": [(11, 19, "PERSONAJE")]}),
    ("‘Order of Merlin, Second Class, I’d say. First Class, if I can wangle it!’", 
     {"entities": [(1, 17, "OBJETO_MAGICO")]}),
    ("‘As a matter of fact, it was Potter, Weasley and Granger, Minister …’", 
     {"entities": [(30, 36, "PERSONAJE"), (38, 45, "PERSONAJE"), (50, 57, "PERSONAJE"), (59, 67, "PERSONAJE")]}),
    ("Black had bewitched them, I saw it immediately. A Confundus Charm, to judge by their behaviour.", 
     {"entities": [(0, 5, "PERSONAJE"), (51, 67, "HECHIZO")]}),
    ("... and of course Potter has always been allowed an extraordinary amount of licence by the Headmaster –’", 
     {"entities": [(19, 25, "PERSONAJE"), (94, 105, "PERSONAJE")]}),
    ("‘What amazes me most is the behaviour of the Dementors … you’ve really no idea what made them retreat, Snape?’", 
     {"entities": [(42, 52, "PERSONAJE"), (106, 111, "PERSONAJE")]}),
    ("‘All unconscious by the time I reached them. I bound and gagged Black, naturally, conjured stretchers and brought them all straight back to the castle.’", 
     {"entities": [(66, 71, "PERSONAJE")]}),
    ("At the very end of the ward, he could make out Madam Pomfrey with her back to him, bending over a bed.", 
     {"entities": [(49, 62, "PERSONAJE")]}),
    ("Ron’s red hair was visible beneath Madam Pomfrey’s arm.", 
     {"entities": [(0, 3, "PERSONAJE"), (36, 49, "PERSONAJE")]}),
    ("In the bed to his right lay Hermione. Moonlight was falling across her bed.", 
     {"entities": [(29, 37, "PERSONAJE")]}),
    ("It was ajar, and the voices of Cornelius Fudge and Snape were coming through it from the corridor outside.", 
     {"entities": [(32, 48, "PERSONAJE"), (53, 58, "PERSONAJE")]}),
    ("The Dementors will be performing the Kiss any moment now –’", 
     {"entities": [(4, 14, "PERSONAJE"), (34, 38, "OBJETO_MAGICO")]}),
    ("‘Sirius Black’s innocent! Peter Pettigrew faked his own death! We saw him tonight!", 
     {"entities": [(1, 13, "PERSONAJE"), (27, 42, "PERSONAJE")]}),
    ("It was Ron’s rat, he’s an Animagus, Pettigrew, I mean, and –’", 
     {"entities": [(7, 10, "PERSONAJE"), (12, 15, "PERSONAJE"), (24, 32, "OBJETO_MAGICO"), (34, 43, "PERSONAJE")]}),
    ("The door opened again. It was Dumbledore.", 
     {"entities": [(31, 41, "PERSONAJE")]}),
    ("‘That, indeed, is Black’s story’ said Dumbledore, surveying Snape closely through his half-moon spectacles.", 
     {"entities": [(20, 25, "PERSONAJE"), (36, 46, "PERSONAJE"), (58, 63, "PERSONAJE"), (84, 105, "OBJETO_MAGICO")]}),
    ("‘Peter Pettigrew was not in the Shrieking Shack, nor did I see any sign of him in the grounds.’", 
     {"entities": [(1, 16, "PERSONAJE"), (32, 48, "LUGAR")]}),
    ("You must see that Professor Snape’s version of events is far more convincing than yours.’", 
     {"entities": [(22, 36, "PERSONAJE")]}),
    ("The attack on the Fat Lady – entering Gryffindor Tower with a knife – without Pettigrew, alive or dead, we have no chance of overturning Sirius’ sentence.’", 
     {"entities": [(19, 27, "PERSONAJE"), (39, 56, "LUGAR"), (68, 77, "PERSONAJE"), (127, 133, "PERSONAJE")]}),
    ("‘Sirius is locked in Professor Flitwick’s office on the seventh floor.", 
     {"entities": [(1, 7, "PERSONAJE"), (23, 41, "PERSONAJE")]}),
    ("‘I am going to lock you in. It is –’ he consulted his watch, ‘five minutes to midnight. Miss Granger, three turns should do it. Good luck.’", 
     {"entities": [(82, 94, "PERSONAJE")]}),
    ("She was holding the chain out. He saw a tiny, sparkling hourglass hanging from it.", 
     {"entities": [(56, 65, "OBJETO_MAGICO")]}),
    ("‘It’s called a Time-Turner,’ Hermione whispered, ‘and I got it from Professor McGonagall on our first day back.", 
     {"entities": [(15, 27, "OBJETO_MAGICO"), (30, 38, "PERSONAJE"), (64, 84, "PERSONAJE")]}),
    ("She had to write all sorts of letters to the Ministry of Magic so I could have one.", 
     {"entities": [(42, 59, "LUGAR")]}),
    ("‘Hermione, we’re going to save Buckbeak!’", 
     {"entities": [(1, 9, "PERSONAJE"), (31, 39, "PERSONAJE")]}),
    ("Dumbledore, Fudge, the old Committee member, and Macnair the executioner were coming down the steps.", 
     {"entities": [(0, 10, "PERSONAJE"), (12, 17, "PERSONAJE"), (49, 56, "PERSONAJE")]}),
    ("‘There’s only one thing it could have been, to make the Dementors go,’ said Harry. ‘A real Patronus. A powerful one.’", 
     {"entities": [(55, 65, "PERSONAJE"), (77, 82, "PERSONAJE"), (91, 99, "OBJETO_MAGICO")]}),
    ("He was thinking about his father, and about his three oldest friends … Moony, Wormtail, Padfoot and Prongs …", 
     {"entities": [(68, 73, "PERSONAJE"), (75, 84, "PERSONAJE"), (86, 93, "PERSONAJE"), (98, 104, "PERSONAJE")]}),
    ("And then it hit him – he understood. He hadn’t seen his father – he had seen himself –", 
     {"entities": []}),
    ("‘EXPECTO PATRONUM!’ he yelled.", 
     {"entities": [(1, 17, "HECHIZO")]}),
    ("‘Stand back!’ Hermione called to him, and she took out her wand, still gripping the back of Harry’s robes with her left hand.", 
     {"entities": [(13, 21, "PERSONAJE"), (54, 58, "OBJETO_MAGICO"), (82, 87, "PERSONAJE")]}),
    ("‘Alohomora!’", 
     {"entities": [(1, 10, "HECHIZO")]}),
    ("‘We’ll see each other again,’ he said. ‘You are – truly your father’s son, Harry …’", 
     {"entities": [(73, 78, "PERSONAJE")]}),
    ("Harry felt his feet slam into the ground; his injured leg gave way, and he fell forward; his hand let go of the Triwizard Cup at last.", 
     {"entities": [(0, 5, "PERSONAJE"), (104, 118, "OBJETO_MAGICO")]}),
    ("They had left the Hogwarts grounds completely; they had obviously traveled miles - perhaps hundreds of miles - for even the mountains surrounding the castle were gone.", 
     {"entities": [(19, 27, "LUGAR")]}),
    ("“Did anyone tell you the cup was a Portkey?” he asked.", 
     {"entities": [(34, 41, "OBJETO_MAGICO")]}),
    ("They both turned back to watch the approaching figure.", 
     {"entities": []}),
    ("From far away, above his head, he heard a high, cold voice say, “Kill the spare.”", 
     {"entities": []}),
    ("A swishing noise and a second voice, which screeched the words to the night: “Avada Kedavra!”", 
     {"entities": [(78, 92, "HECHIZO")]}),
    ("Cedric was lying spread-eagled on the ground beside him. He was dead.", 
     {"entities": [(0, 6, "PERSONAJE")]}),
    ("The short man in the cloak had put down his bundle, lit his wand, and was dragging Harry toward the marble headstone.", 
     {"entities": [(61, 65, "OBJETO_MAGICO"), (82, 87, "PERSONAJE")]}),
    ("TOM RIDDLE", 
     {"entities": [(0, 10, "PERSONAJE")]}),
    ("And Harry realized who was under the hood. It was Wormtail.", 
     {"entities": [(4, 9, "PERSONAJE"), (49, 57, "PERSONAJE")]}),
    ("He looked down and saw a gigantic snake slithering through the grass, circling the headstone where he was tied.", 
     {"entities": [(34, 39, "PERSONAJE")]}),
    ("The thing Wormtail had been carrying had the shape of a crouched human child, except that Harry had never seen anything less like a child.", 
     {"entities": [(10, 18, "PERSONAJE"), (86, 91, "PERSONAJE")]}),
    ("And then Wormtail lowered the creature into the cauldron; there was a hiss, and it vanished below the surface", 
     {"entities": [(10, 18, "PERSONAJE")]}),
    ("“Bone of the father, unknowingly given, you will renew your son!”", 
     {"entities": []}),
    ("He stretched his right hand out in front of him - the hand with the missing finger.", 
     {"entities": []}),
    ("“B-blood of the enemy…forcibly taken…you will…resurrect your foe.”", 
     {"entities": []}),
    ("He staggered back to the cauldron with Harry's blood.", 
     {"entities": [(40, 45, "PERSONAJE")]}),
    ("The thin man stepped out of the cauldron, staring at Harry…and Harry stared back into the face that had haunted his nightmares for three years.", 
     {"entities": [(55, 60, "PERSONAJE"), (66, 71, "PERSONAJE")]}),
    ("Lord Voldemort had risen again.", 
     {"entities": [(0, 14, "PERSONAJE")]}),
     ("To me, Potter,' repeated the drawling voice of Lucius Malfoy as he held out his hand, palm up.",
     {"entities": [(7, 13, "PERSONAJE"), (47, 61, "PERSONAJE")]}),
    ("'Where's Sirius?' Harry said.",
     {"entities": [(8, 14, "PERSONAJE"), (17, 22, "PERSONAJE")]}),
    ("Several of the Death Eaters laughed; a harsh female voice from the midst of the shadowy figures to Harry's left said triumphantly, The Dark Lord always knows!'",
     {"entities": [(15, 28, "PERSONAJE"), (105, 110, "PERSONAJE"), (129, 138, "PERSONAJE")]}),
    ("'I want to know where Sirius is!' mimicked the woman to his left.",
     {"entities": [(23, 29, "PERSONAJE")]}),
    ("'You've got him,' said Harry, ignoring the rising panic in his chest, the dread he had been fighting since they had first entered the ninety-seventh row.",
     {"entities": [(23, 28, "PERSONAJE")]}),
    ("'Oh, you don't know Potter as I do, Bellatrix,' said Malfoy softly.",
     {"entities": [(22, 28, "PERSONAJE"), (36, 45, "PERSONAJE"), (53, 59, "PERSONAJE")]}),
    ("'It's time you learned the difference between life and dreams, Potter,' said Malfoy.",
     {"entities": [(61, 67, "PERSONAJE"), (75, 81, "PERSONAJE")]}),
    ("As he did so, the five wands of Ron, Hermione, Neville, Ginny and Luna rose on either side of him.",
     {"entities": [(23, 29, "OBJETO_MAGICO"), (33, 36, "PERSONAJE"), (38, 46, "PERSONAJE"), (48, 55, "PERSONAJE"), (57, 62, "PERSONAJE"), (67, 71, "PERSONAJE")]}),
    ("The words were hardly out of his mouth when the female Death Eater shrieked: 'Accto proph—'",
     {"entities": [(57, 69, "PERSONAJE"), (80, 85, "HECHIZO")]}),
    ("Harry was just ready for her: he shouted 'Protego!' before she had finished her spell, and though the glass sphere slipped to the tips of his fingers he managed to cling on to it.",
     {"entities": [(0, 5, "PERSONAJE"), (42, 50, "HECHIZO")]}),
    ("Azkaban had hollowed Bellatrix Lestrange's face, making it gaunt and skull-like, but it was alive with a feverish, fanatical glow.",
     {"entities": [(0, 7, "LUGAR"), (23, 43, "PERSONAJE")]}),
    ("'How come Voldemort wants it?'",
     {"entities": [(9, 18, "PERSONAJE")]}),
    ("'Did you know he's a half-blood too?' said Harry recklessly. Hermione gave a little moan in his ear.",
     {"entities": [(45, 50, "PERSONAJE"), (53, 61, "PERSONAJE")]}),
    ("A jet of red light had shot from the end of Bellatrix Lestrange's wand, but Malfoy had deflected it;",
     {"entities": [(46, 66, "PERSONAJE"), (73, 77, "OBJETO_MAGICO"), (83, 89, "PERSONAJE")]}),
    ("'Dumbledore never told you the reason you bear that scar was hidden in the bowels of the Department of Mysteries?' Malfoy sneered.",
     {"entities": [(1, 11, "PERSONAJE"), (51, 55, "OBJETO_MAGICO"), (85, 108, "LUGAR"), (111, 117, "PERSONAJE")]}),
    ("'And why did he want to steal a prophecy about me?'",
     {"entities": [(34, 42, "OBJETO_MAGICO")]}),
    ("The Dark Lord, walk into the Ministry of Magic, when they are so sweetly ignoring his return?",
     {"entities": [(0, 13, "PERSONAJE"), (28, 45, "LUGAR")]}),
    ("Five different voices behind him bellowed, 'REDUCTO!'",
     {"entities": [(44, 52, "HECHIZO")]}),
    ("he heard Hermione shout, 'Stupefy!'",
     {"entities": [(9, 17, "PERSONAJE"), (26, 33, "HECHIZO")]}),
    ("'Colloportus!' gasped Hermione and the door sealed itself with an odd squelching noise.",
     {"entities": [(1, 12, "HECHIZO"), (21, 29, "PERSONAJE")]}),
    ("'Listen!' whispered Neville.",
     {"entities": [(19, 26, "PERSONAJE")]}),
    ("Harry put his ear close to the door to listen and heard Lucius Malfoy roar, 'Leave Nott, leave him, I say —",
     {"entities": [(0, 5, "PERSONAJE"), (56, 69, "PERSONAJE"), (77, 81, "PERSONAJE")]}),
    ("Bellatrix, Rodolphus, you take the left; Crabbe, Rabastan, go right -Jugson, Dolohov, the door straight ahead - Macnair and Avery, through here - Rookwood, over there - Mulciber, come with me!'",
     {"entities": [(0, 9, "PERSONAJE"), (11, 20, "PERSONAJE"), (41, 47, "PERSONAJE"), (49, 57, "PERSONAJE"), (68, 74, "PERSONAJE"), (76, 83, "PERSONAJE"), (116, 123, "PERSONAJE"), (128, 133, "PERSONAJE"), (148, 156, "PERSONAJE"), (172, 180, "PERSONAJE")]}),
    ("'Stand aside!' said a rough voice. 'Alahomora!'",
     {"entities": [(34, 43, "HECHIZO")]}),
    ("poking his wand out from under the desk, he shouted, 'STUPEFY!'",
     {"entities": [(12, 16, "OBJETO_MAGICO"), (53, 61, "HECHIZO")]}),
    ("Neville overturned a desk in his anxiety to help; and pointing his wand wildly at the struggling pair, he cried: 'EXPELLIARMUS!'",
     {"entities": [(0, 7, "PERSONAJE"), (66, 70, "OBJETO_MAGICO"), (122, 135, "HECHIZO")]}),
    ("'Get out of the way, Harry!' yelled Neville, clearly determined to repair the damage.",
     {"entities": [(22, 27, "PERSONAJE"), (35, 42, "PERSONAJE")]}),
    ("'STUPEFY!' screamed Hermione, who had just caught up with them.",
     {"entities": [(1, 9, "HECHIZO"), (19, 27, "PERSONAJE")]}),
    ("'Accio wand!' cried Hermione.",
     {"entities": [(1, 11, "HECHIZO"), (19, 27, "PERSONAJE")]}),
    ("All three of them raised their wands again, but none of them struck: they were all gazing, open-mouthed, appalled, at what was happening to the man's head.",
     {"entities": [(30, 35, "OBJETO_MAGICO")]}),
    ("The Death Eater had pulled his head out of the bell jar.",
     {"entities": [(4, 16, "PERSONAJE")]}),
    ("With a cry of triumph, both yelled: 'IMPEDIMENTA!'",
     {"entities": [(37, 48, "HECHIZO")]}),
    ("'Silencio!' cried Hermione and the man's voice was extinguished.",
     {"entities": [(1, 9, "HECHIZO"), (17, 25, "PERSONAJE")]}),
    ("'Petrificus Totalus!' shouted Harry, as the second Death Eater raised his wand.",
     {"entities": [(1, 19, "HECHIZO"), (29, 34, "PERSONAJE"), (51, 63, "PERSONAJE"), (73, 77, "OBJETO_MAGICO")]}),
    ("...from the Daily Prophet: Antonin Dolohov, the wizard who had murdered the Prewetts.",
     {"entities": [(11, 24, "OBJETO_MAGICO"), (26, 42, "PERSONAJE")]}),
    ("'She's alive?'",
     {"entities": []}),
    ("My gran's going do kill be,' said Neville thickly, blood spattering from his nose as he spoke, 'dat was by dad's old wand.'",
     {"entities": [(36, 43, "PERSONAJE"), (120, 124, "OBJETO_MAGICO")]}),
    ("As the door flew open, Harry, Hermione and Neville dived under desks.",
     {"entities": [(24, 29, "PERSONAJE"), (31, 39, "PERSONAJE"), (44, 51, "PERSONAJE")]}),
    ("A spell hit the stone bench at Harrys heel; it crumbled away and he fell back to the step below.",
     {"entities": [(31, 36, "PERSONAJE")]}),
    ("The second jet of light hit him squarely on the chest.",
     {"entities": []}),
    ("Harry heard Bellatrix Lestrange's triumphant scream, but knew it meant nothing - Sirius had only just fallen through the archway, he would reappear from the other side any second…",
     {"entities": [(12, 32, "PERSONAJE"), (70, 76, "PERSONAJE")]}),
    ("Once back under the starry sky, Harry heaved Dumbledore on to the top of the nearest boulder and then to his feet.",
     {"entities": [(34, 39, "PERSONAJE"), (47, 57, "PERSONAJE")]}),
    ("'We did it, Professor!' Harry whispered with difficulty; he suddenly realised that he had a searing stitch in his chest.",
     {"entities": [(23, 28, "PERSONAJE")]}),
    ("'We did it! We got the Horcrux!'",
     {"entities": [(22, 29, "OBJETO_MAGICO")]}),
    ("‘Sir, are you all right?’",
     {"entities": []}),
    ("‘We need to get you up to the school, sir … Madam Pomfrey …’",
     {"entities": [(29, 35, "LUGAR"), (44, 57, "PERSONAJE")]}),
    ("‘Severus,’ said Dumbledore clearly. ‘I need Severus …’",
     {"entities": [(1, 8, "PERSONAJE"), (16, 26, "PERSONAJE"), (38, 45, "PERSONAJE")]}),
    ("...and looking around he saw Madam Rosmerta scurrying down the dark street towards them on highheeled, fluffy slippers...",
     {"entities": [(29, 44, "PERSONAJE")]}),
    ("The - the Dark Mark, Albus.’",
     {"entities": [(11, 20, "OBJETO_MAGICO"), (22, 27, "PERSONAJE")]}),
    ("There it was, hanging in the sky above the school: the blazing green skull with a serpent tongue, the mark Death Eaters left behind whenever they had entered a building … wherever they had murdered …",
     {"entities": [(44, 56, "PERSONAJE")]}),
    ("‘We need to return to the castle at once,’ said Dumbledore.",
     {"entities": [(26, 32, "LUGAR"), (44, 54, "PERSONAJE")]}),
    ("‘Accio Rosmerta’s brooms.’",
     {"entities": [(1, 6, "HECHIZO"), (7, 15, "PERSONAJE"), (18, 24, "OBJETO_MAGICO")]}),
    ("Harry pulled his Cloak out of his pocket and threw it over himself before mounting his broom; Madam Rosmerta was already tottering back towards her pub as Harry and Dumbledore kicked off from the ground and rose up into the air.",
     {"entities": [(0, 5, "PERSONAJE"), (17, 22, "OBJETO_MAGICO"), (82, 90, "OBJETO_MAGICO"), (92, 107, "PERSONAJE"), (134, 139, "PERSONAJE"), (144, 154, "PERSONAJE")]}),
    ("The Dark Mark was glittering directly above the Astronomy Tower, the highest of the castle.",
     {"entities": [(4, 13, "OBJETO_MAGICO"), (47, 64, "LUGAR")]}),
    ("‘Go and wake Severus,’ said Dumbledore faintly but clearly.",
     {"entities": [(13, 20, "PERSONAJE"), (28, 38, "PERSONAJE")]}),
    ("Then, by the light of the Mark, he saw Dumbledore’s wand flying in an arc over the edge of the ramparts and understood …",
     {"entities": [(39, 49, "PERSONAJE"), (50, 54, "OBJETO_MAGICO")]}),
    ("‘Good evening, Draco.’",
     {"entities": [(15, 20, "PERSONAJE")]}),
    ("‘No,’ he said. ‘I’ve got backup. There are Death Eaters here in your school tonight.’",
     {"entities": [(44, 56, "PERSONAJE")]}),
    ("‘Draco, Draco, you are not a killer.’",
     {"entities": [(1, 6, "PERSONAJE"), (8, 13, "PERSONAJE")]}),
    ("‘Oh, yes, I do,’ said Dumbledore mildly.",
     {"entities": [(23, 33, "PERSONAJE")]}),
    ("You almost killed Katie Bell and Ronald Weasley.",
     {"entities": [(19, 29, "PERSONAJE"), (34, 49, "PERSONAJE")]}),
    ("That was clever … there is a pair, I take it?’",
     {"entities": []}),
    ("‘The other’s in Borgin and Burkes,’ said Malfoy, ‘and they make a kind of passage between them.",
     {"entities": [(18, 35, "LUGAR"), (43, 49, "PERSONAJE")]}),
    ("‘He’s a doubleagent, you stupid old man, he isn’t working for you, you just think he is!’",
     {"entities": []}),
    ("‘I didn’t,’ breathed Malfoy. He was not looking at Greyback; he did not seem to want to even glance at him.",
     {"entities": [(21, 27, "PERSONAJE"), (51, 59, "PERSONAJE")]}),
    ("‘Now, Draco, quickly!’ said the brutalfaced man angrily.",
     {"entities": [(6, 11, "PERSONAJE")]}),
    ("‘Til do it,’ snarled Greyback, moving towards Dumbledore with his hands outstretched, his teeth bared.",
     {"entities": [(21, 29, "PERSONAJE"), (45, 55, "PERSONAJE")]}),
    ("‘We’ve got a problem, Snape,’ said the lumpy Amycus, whose eyes and wand were fixed alike upon Dumbledore, ‘the boy doesn’t seem able -’",
     {"entities": [(24, 29, "PERSONAJE"), (47, 53, "PERSONAJE"), (84, 94, "PERSONAJE")]}),
    ("Snape gazed for a moment at Dumbledore, and there was revulsion and hatred etched in the harsh lines of his face.",
     {"entities": [(0, 5, "PERSONAJE"), (29, 39, "PERSONAJE")]}),
    ("‘Severus … please …”",
     {"entities": [(1, 8, "PERSONAJE")]}),
    ("A jet of green light shot from the end of Snape’s wand and hit Dumbledore squarely in the chest.",
     {"entities": [(42, 47, "PERSONAJE"), (48, 52, "OBJETO_MAGICO"), (61, 71, "PERSONAJE")]}),
     ("His job was to walk calmly into Death’s welcoming arms. Along the way, he was to dispose of Voldemort’s remaining links to life...",
     {"entities": [(92, 102, "PERSONAJE")]}),
    ("...the job that ought to have been done in Godric’s Hollow would be finished.",
     {"entities": [(42, 58, "LUGAR")]}),
    ("If he could only have died on that summer’s night when he had left number four, Privet Drive, for the last time...",
     {"entities": [(80, 92, "LUGAR")]}),
    ("If he could only have died like Hedwig, so quickly he would not have known it had happened!",
     {"entities": [(31, 37, "PERSONAJE")]}),
    ("Dumbledore’s betrayal was almost nothing.",
     {"entities": [(0, 10, "PERSONAJE")]}),
    ("Dumbledore had passed the job of destroying them to him, and obediently he had continued to chip away at the bonds tying not only Voldemort, but himself, to life!",
     {"entities": [(0, 10, "PERSONAJE"), (126, 136, "PERSONAJE")]}),
    ("The images of Fred, Lupin, and Tonks lying dead in the Great Hall forced their way back into his mind’s eye...",
     {"entities": [(15, 19, "PERSONAJE"), (21, 26, "PERSONAJE"), (32, 37, "PERSONAJE"), (54, 65, "LUGAR")]}),
    ("He had failed: The snake survived. One Horcrux remained to bind Voldemort to the earth, even after Harry had been killed.",
     {"entities": [(19, 24, "PERSONAJE"), (37, 45, "OBJETO_MAGICO"), (61, 71, "PERSONAJE"), (89, 94, "PERSONAJE")]}),
    ("Ron and Hermione would know what needed to be done, of course . . .",
     {"entities": [(0, 3, "PERSONAJE"), (8, 16, "PERSONAJE")]}),
    ("That would have been why Dumbledore wanted him to confide in two others . . .",
     {"entities": [(26, 36, "PERSONAJE")]}),
    ("Harry pulled the Invisibility Cloak over himself and descended through the floors, at last walking down the marble staircase into the entrance hall.",
     {"entities": [(0, 5, "PERSONAJE"), (17, 35, "OBJETO_MAGICO")]}),
    ("Then Neville nearly walked into him.",
     {"entities": [(5, 12, "PERSONAJE")]}),
    ("Harry glanced down and felt another dull blow to his stomach: Colon Creevey, though underage, must have sneaked back just as Malfoy, Crabbe, and Goyle had done.",
     {"entities": [(0, 5, "PERSONAJE"), (61, 74, "PERSONAJE"), (124, 130, "PERSONAJE"), (132, 138, "PERSONAJE"), (144, 149, "PERSONAJE")]}),
    ("“You know what? I can manage him alone, Neville,” said Oliver Wood, and he heaved Colin over his shoulder in a fireman’s lift and carried him into the Great Hall.",
     {"entities": [(43, 50, "PERSONAJE"), (58, 69, "PERSONAJE"), (82, 87, "PERSONAJE"), (153, 164, "LUGAR")]}),
    ("He felt he would have given all the time remaining to him for just one last look at them; but then, would he ever have the strength to stop looking?",
     {"entities": []}),
    ("“Harry!” Neville looked suddenly scared. “Harry, you’re not thinking of handing yourself over?”",
     {"entities": [(1, 6, "PERSONAJE"), (8, 15, "PERSONAJE"), (42, 47, "PERSONAJE")]}),
    ("You know Voldemort’s snake. Neville? He’s got a huge snake . . . Calls it Nagini . . .”",
     {"entities": [(8, 18, "PERSONAJE"), (19, 24, "PERSONAJE"), (26, 33, "PERSONAJE"), (52, 57, "PERSONAJE"), (74, 80, "PERSONAJE")]}),
    ("“Kill the snake,” Harry repeated.",
     {"entities": [(13, 18, "PERSONAJE"), (21, 26, "PERSONAJE")]}),
    ("Dumbledore had died knowing that three people still knew about the Horcruxes; now Neville would take Harry’s place: There would still be three in the secret.",
     {"entities": [(0, 10, "PERSONAJE"), (69, 78, "OBJETO_MAGICO"), (85, 92, "PERSONAJE"), (104, 109, "PERSONAJE")]}),
    ("He was feet away from her when he realized it was Ginny.",
     {"entities": [(50, 55, "PERSONAJE")]}),
    ("Hagrid’s hut loomed out of the darkness. There were no lights, no sound of Fang scrabbling at the door, his bark booming in welcome.",
     {"entities": [(0, 7, "PERSONAJE"), (70, 74, "PERSONAJE")]}),
    ("He moved on, and now he reached the edge of the forest, and he stopped.",
     {"entities": [(47, 53, "LUGAR")]}),
    ("A swarm of dementors was gliding amongst the trees; he could feel their chill, and he was not sure he would be able to pass safely through it.",
     {"entities": [(11, 20, "PERSONAJE")]}),
    ("He had not strength left for a Patronus.",
     {"entities": [(31, 39, "OBJETO_MAGICO")]}),
    ("The long game was ended, the Snitch had been caught, it was time to leave the air. . . .",
     {"entities": [(29, 35, "OBJETO_MAGICO")]}),
    ("He lowered his shaking hand, raised Draco’s wand beneath the Cloak, and murmured, “Lumos.”",
     {"entities": [(36, 41, "PERSONAJE"), (42, 46, "OBJETO_MAGICO"), (56, 61, "OBJETO_MAGICO"), (77, 83, "HECHIZO")]}),
    ("The Resurrection Stone had cracked down the vertical line representing the Elder Wand.",
     {"entities": [(4, 24, "OBJETO_MAGICO"), (79, 90, "OBJETO_MAGICO")]}),
    ("They resembled most closely the Riddle that had escaped from the diary so long ago...",
     {"entities": [(31, 37, "PERSONAJE"), (58, 63, "OBJETO_MAGICO")]}),
    ("James was exactly the same height as Harry.",
     {"entities": [(0, 5, "PERSONAJE"), (36, 41, "PERSONAJE")]}),
    ("Sirius was tall and handsome, and younger by far than Harry had seen him in life.",
     {"entities": [(0, 6, "PERSONAJE"), (50, 55, "PERSONAJE")]}),
    ("Lupin was younger too, and much less shabby, and his hair was thicker and darker.",
     {"entities": [(0, 5, "PERSONAJE")]}),
    ("Lily’s smile was widest of all.",
     {"entities": [(0, 4, "PERSONAJE")]}),
    ("“Dying? Not at all,” said Sirius. “Quicker and easier than falling asleep.”",
     {"entities": [(27, 33, "PERSONAJE")]}),
    ("“And he will want it to be quick. He wants it over,” said Lupin.",
     {"entities": [(59, 64, "PERSONAJE")]}),
    ("“--- right after you’d had your son . . . Remus, I’m sorry ---“",
     {"entities": [(40, 45, "PERSONAJE")]}),
    ("“We are part of you,” said Sirius. “Invisible to anyone else.”",
     {"entities": [(28, 34, "PERSONAJE")]}),
    ("Two figures emerged from behind a nearby tree: Their wands flared, and Harry saw Yaxley and Dolohov peering into the darkness...",
     {"entities": [(66, 70, "OBJETO_MAGICO"), (79, 84, "PERSONAJE"), (89, 95, "PERSONAJE"), (100, 107, "PERSONAJE")]}),
    ("“That head case Hagrid kept a whole bunch of stuff in here,” said Dolohov, glancing over his shoulder.",
     {"entities": [(16, 22, "PERSONAJE"), (61, 68, "PERSONAJE")]}),
    ("They had traveled on mere minutes when Harry saw light ahead, and Yaxley and Dolohov stepped out into a clearing that Harry knew had been the place where the monstrous Aragog had once lived.",
     {"entities": [(38, 43, "PERSONAJE"), (64, 70, "PERSONAJE"), (75, 82, "PERSONAJE"), (104, 109, "PERSONAJE"), (150, 156, "PERSONAJE")]}),
    ("...the swarms of descendants he had spawned had been driven out by the Death Eaters, to fight for their cause.",
     {"entities": [(70, 82, "PERSONAJE")]}),
    ("Harry saw Fenrir, skulking, chewing his long nails; the great blond Rowle was dabbing at his bleeding lip.",
     {"entities": [(0, 5, "PERSONAJE"), (10, 16, "PERSONAJE"), (67, 72, "PERSONAJE")]}),
    ("He saw Lucius Malfoy, who looked defeated and terrified, and Narcissa, whose eyes were sunken and full of apprehension.",
     {"entities": [(7, 21, "PERSONAJE"), (63, 71, "PERSONAJE")]}),
    ("Behind his head, still swirling and coiling, the great snake Nagini floated in her glittering, charmed cage, like a monstrous halo.",
     {"entities": [(55, 60, "PERSONAJE"), (61, 67, "PERSONAJE")]}),
    ("Bellatrix had spoken: She sat closest to Voldemort, disheveled, her face a little bloody but otherwise unharmed.",
     {"entities": [(0, 9, "PERSONAJE"), (42, 52, "PERSONAJE")]}),
    ("He did not want to be tempted to fight.",
     {"entities": []}),
    ("The Resurrection Stone slipped from between his numb fingers, and out of the corner of his eyes he saw his parents, Sirius, and Lupin vanish as he stepped forward into the firelight.",
     {"entities": [(4, 24, "OBJETO_MAGICO"), (123, 129, "PERSONAJE"), (135, 140, "PERSONAJE")]}),
    ("He turned: Hagrid was bound and trussed, tied to a tree nearby.",
     {"entities": [(11, 17, "PERSONAJE")]}),
    ("“QUIET!” shouted Rowle, and with a flick of his wand, Hagrid was silenced.",
     {"entities": [(17, 22, "PERSONAJE"), (45, 50, "OBJETO_MAGICO"), (52, 58, "PERSONAJE")]}),
     ("“But I thought — Snape —”", 
     {"entities": [(18, 23, "PERSONAJE")]}),
    ("Next to him, who would suspect p-p-poor, st-stuttering P-Professor Quirrell?”", 
     {"entities": [(60, 78, "PERSONAJE")]}),
    ("I’d have managed it before then if Snape hadn’t been muttering a countercurse, trying to save you.”", 
     {"entities": [(34, 39, "PERSONAJE"), (63, 75, "OBJETO_MAGICO")]}),
    ("Funny, really…he needn’t have bothered. I couldn’t do anything with Dumbledore watching.", 
     {"entities": [(70, 80, "PERSONAJE")]}),
    ("All the other teachers thought Snape was trying to stop Gryffindor from winning...", 
     {"entities": [(32, 37, "PERSONAJE"), (53, 63, "CASA_HOGWARTS")]}),
    ("...not only did my troll fail to beat you to death, that three-headed dog didn’t even manage to bite Snape’s leg off properly.", 
     {"entities": [(21, 26, "PERSONAJE"), (56, 71, "PERSONAJE"), (105, 110, "PERSONAJE")]}),
    ("“This mirror is the key to finding the Stone,” Quirrell murmured, tapping his way around the frame.", 
     {"entities": [(36, 41, "OBJETO_MAGICO"), (44, 52, "PERSONAJE")]}),
     ("“I see the Stone…I’m presenting it to my master…but where is it?”", 
     {"entities": [(8, 13, "OBJETO_MAGICO")]}),
    ("He was at Hogwarts with your father, didn’t you know? They loathed each other.", 
     {"entities": [(11, 19, "LUGAR")]}),
    ("...he is a great wizard and I am weak —”", 
     {"entities": []}),
    ("He is with me wherever I go,” said Quirrell quietly.", 
     {"entities": [(35, 43, "PERSONAJE")]}),
    ("“I see myself shaking hands with Dumbledore,” he invented.", 
     {"entities": [(32, 42, "PERSONAJE")]}),
    ("Quirrell cursed again.", 
     {"entities": [(0, 8, "PERSONAJE")]}),
    ("So he knew. The feeling suddenly surged back into Harry’s legs.", 
     {"entities": [(51, 56, "PERSONAJE")]}),
    ("“LIAR!” Harry shouted suddenly.", 
     {"entities": [(8, 13, "PERSONAJE")]}),
    ("Quirrell was walking backward at him, so that Voldemort could still see him.", 
     {"entities": [(0, 8, "PERSONAJE"), (46, 55, "PERSONAJE")]}),
    ("“Good afternoon, Harry,” said Dumbledore.", 
     {"entities": [(17, 22, "PERSONAJE"), (29, 39, "PERSONAJE")]}),
    ("“Then who does? Sir, I —”", 
     {"entities": []}),
    ("“But sir, the Stone —”", 
     {"entities": [(15, 20, "OBJETO_MAGICO")]}),
    ("“Oh, you know about Nicolas?” said Dumbledore, sounding quite delighted.", 
     {"entities": [(21, 28, "PERSONAJE"), (35, 45, "PERSONAJE")]}),
    ("...to the well-organized mind, death is but the next great adventure.’”", 
     {"entities": []}),
    ("“Yes, him — Quirrell said he hates me because he hated my father. Is that true?”", 
     {"entities": [(12, 20, "PERSONAJE")]}),
    ("Well, they did rather detest each other. Not unlike yourself and Mr. Malfoy.", 
     {"entities": [(66, 76, "PERSONAJE")]}),
    ("How did I get the Stone out of the mirror?", 
     {"entities": [(15, 20, "OBJETO_MAGICO")]}),
    ("“The whole school’s talking about it,” said Ron.", 
     {"entities": [(43, 46, "PERSONAJE")]}),
    ("A huge banner showing the Slytherin serpent covered the wall behind the High Table.",
     {"entities": [(25, 34, "CASA_HOGWARTS")]}),
    ("Ravenclaw has four hundred and twenty-six and Slytherin, four hundred and seventy-two.”",
     {"entities": [(0, 9, "CASA_HOGWARTS"), (44, 53, "CASA_HOGWARTS")]}),
    ("He, Ron, and Hermione passed through the gateway together.",
     {"entities": [(4, 7, "PERSONAJE"), (12, 20, "PERSONAJE")]}),
    ("“You must be Harry’s family!” said Mrs. Weasley.",
     {"entities": [(15, 20, "PERSONAJE"), (36, 47, "PERSONAJE")]}),
    ("“In a manner of speaking,” said Uncle Vernon.",
     {"entities": [(31, 43, "PERSONAJE")]}),
    ("His heart beating very fast, Harry stood listening to the chill silence.",
     {"entities": [(29, 34, "PERSONAJE")]}),
    ("Lying open there was the little black diary Harry had found in Moaning Myrtle’s bathroom.",
     {"entities": [(39, 44, "OBJETO_MAGICO"), (45, 50, "PERSONAJE"), (64, 78, "LUGAR")]}),
    ("“Are you a ghost?” Harry said uncertainly.",
     {"entities": [(10, 15, "PERSONAJE"), (18, 23, "PERSONAJE")]}),
    ("Haven’t you guessed yet, Harry Potter?” said Riddle softly.",
     {"entities": [(26, 38, "PERSONAJE"), (45, 51, "PERSONAJE")]}),
    ("It had taken me five whole years to find out everything I could about the Chamber of Secrets and discover the secret entrance...",
     {"entities": [(70, 89, "LUGAR")]}),
    ("He pulled Harry’s wand from his pocket and began to trace it through the air...",
     {"entities": [(9, 14, "PERSONAJE"), (15, 19, "OBJETO_MAGICO")]}),
    ("This is what Dumbledore sends his defender! A songbird and an old hat!",
     {"entities": [(13, 23, "PERSONAJE")]}),
    ("Riddle had the wand. He, Harry, had Fawkes and the Sorting Hat, neither of which would be much good in a duel.",
     {"entities": [(0, 6, "PERSONAJE"), (16, 20, "OBJETO_MAGICO"), (26, 31, "PERSONAJE"), (37, 43, "PERSONAJE"), (48, 59, "OBJETO_MAGICO")]}),
    ("“Kill him.”",
     {"entities": []}),
    ("The basilisk was moving toward Harry; he could hear its heavy body slithering heavily across the dusty floor.",
     {"entities": [(4, 12, "PERSONAJE"), (31, 36, "PERSONAJE")]}),
    ("He felt the bird lay its beautiful head on the spot where the serpent’s fang had pierced him.",
     {"entities": [(66, 79, "OBJETO_MAGICO")]}),
    ("Then, in a rush of wings, Fawkes had soared back overhead and something fell into Harry’s lap — the diary.",
     {"entities": [(27, 33, "PERSONAJE"), (81, 86, "PERSONAJE"), (98, 103, "OBJETO_MAGICO")]}),
    ("“Ron!” Harry yelled, speeding up. “Ginny’s okay! I’ve got her!”",
     {"entities": [(1, 4, "PERSONAJE"), (7, 12, "PERSONAJE"), (31, 36, "PERSONAJE")]}),
     ("‘Nasty cut you’ve got there … Black’s work, I suppose?’", 
     {"entities": [(32, 37, "PERSONAJE")]}),
    ("‘Ah, well, Snape … Harry Potter, you know … we’ve all got a bit of a blind spot where he’s concerned.’", 
     {"entities": [(11, 16, "PERSONAJE"), (19, 31, "PERSONAJE")]}),
    ("I have reason to believe he has been visiting Hogsmeade illegally, too –’", 
     {"entities": [(44, 54, "LUGAR")]}),
    ("‘Extraordinary. And yet Black, and Harry, and the girl –’", 
     {"entities": [(26, 31, "PERSONAJE"), (36, 41, "PERSONAJE")]}),
    ("He was lying in the dark hospital wing.", 
     {"entities": [(26, 40, "LUGAR")]}),
    ("‘Harry Harry, what’s this?’ said Fudge, looking agitated.", 
     {"entities": [(1, 6, "PERSONAJE"), (7, 12, "PERSONAJE"), (31, 36, "PERSONAJE")]}),
    ("‘Minister, listen!’ Harry said. ‘Sirius Black’s innocent!", 
     {"entities": [(1, 9, "PERSONAJE"), (19, 24, "PERSONAJE"), (27, 39, "PERSONAJE")]}),
    ("‘I would like to speak to Harry and Hermione alone,’ said Dumbledore abruptly.", 
     {"entities": [(26, 31, "PERSONAJE"), (36, 44, "PERSONAJE"), (54, 64, "PERSONAJE")]}),
    ("Fudge consulted the large gold pocket watch dangling from his waistcoat.", 
     {"entities": [(0, 5, "PERSONAJE")]}),
    ("‘Sirius Black showed he was capable of murder at the age of sixteen,’ he breathed.", 
     {"entities": [(1, 13, "PERSONAJE")]}),
    ("‘– he escaped when Professor Lupin turned into a werewolf –’", 
     {"entities": [(20, 34, "PERSONAJE"), (49, 57, "PERSONAJE")]}),
    ("But Hermione was fumbling with the neck of her robes, pulling from beneath them a very long, very fine gold chain.", 
     {"entities": [(4, 12, "PERSONAJE")]}),
    ("‘Hermione, what –?’", 
     {"entities": [(1, 9, "PERSONAJE")]}),
    ("‘We’ve gone back in time,’ Hermione whispered, lifting the chain off Harry’s neck in the darkness.", 
     {"entities": [(27, 35, "PERSONAJE"), (64, 69, "PERSONAJE")]}),
    ("‘Footsteps across the hall … yes, I think it’s us going down to Hagrid’s!’", 
     {"entities": [(65, 72, "LUGAR")]}),
    ("‘We’ll have to hide behind a tree or something and keep a lookout –’", 
     {"entities": []}),
    ("Safe in the shadows of the trees, Harry turned around; seconds later, Hermione arrived beside him, panting.", 
     {"entities": [(33, 38, "PERSONAJE"), (62, 70, "PERSONAJE")]}),
    ("They moved quickly behind a wide oak trunk and peered out from either side. Hagrid had appeared in his doorway, shaking and white", 
     {"entities": [(73, 79, "PERSONAJE")]}),
    ("‘That’s Hagrid breaking the milk jug,’ Hermione whispered.", 
     {"entities": [(8, 14, "PERSONAJE"), (37, 45, "PERSONAJE")]}),
     ("He sat up and Hagrid’s heavy coat fell off him.", 
     {"entities": [(14, 20, "PERSONAJE")]}),
    ("...there was an owl rapping its claw on the window, a newspaper held in its beak.", 
     {"entities": [(15, 18, "OBJETO_MAGICO"), (56, 66, "OBJETO_MAGICO")]}),
    ("“Give him five Knuts,” said Hagrid sleepily.", 
     {"entities": [(15, 20, "OBJETO_MAGICO"), (28, 34, "PERSONAJE")]}),
    ("...first stop fer us is Gringotts. Wizards’ bank.", 
     {"entities": [(25, 34, "LUGAR")]}),
    ("Gringotts is the safest place in the world fer anything yeh want ter keep safe — ‘cept maybe Hogwarts.", 
     {"entities": [(0, 9, "LUGAR"), (92, 100, "LUGAR")]}),
    ("Fer Dumbledore. Hogwarts business.” Hagrid drew himself up proudly.", 
     {"entities": [(4, 14, "PERSONAJE"), (16, 24, "LUGAR"), (38, 44, "PERSONAJE")]}),
    ("Hagrid pulled out the pink umbrella again, tapped it twice on the side of the boat, and they sped off toward land.", 
     {"entities": [(0, 6, "PERSONAJE"), (22, 36, "OBJETO_MAGICO")]}),
    ("“Spells — enchantments,” said Hagrid, unfolding his newspaper as he spoke.", 
     {"entities": [(1, 7, "HECHIZO"), (10, 22, "HECHIZO"), (29, 35, "PERSONAJE"), (49, 59, "OBJETO_MAGICO")]}),
    ("They say there’s dragons guardin’ the high security vaults.", 
     {"entities": [(19, 26, "OBJETO_MAGICO")]}),
    ("Hagrid read his newspaper, the Daily Prophet.", 
     {"entities": [(0, 6, "PERSONAJE"), (30, 43, "OBJETO_MAGICO")]}),
    ("“There’s a Ministry of Magic?” Harry asked, before he could stop himself.", 
     {"entities": [(12, 30, "LUGAR"), (33, 38, "PERSONAJE")]}),
    ("...so old Cornelius Fudge got the job.", 
     {"entities": [(10, 25, "PERSONAJE")]}),
    ("Harry took the parchment envelope out of his pocket.", 
     {"entities": [(0, 5, "PERSONAJE"), (16, 36, "OBJETO_MAGICO")]}),
    ("One pair of protective gloves (dragon hide or similar)", 
     {"entities": [(16, 22, "OBJETO_MAGICO"), (24, 36, "OBJETO_MAGICO")]}),
    ("The Standard Book of Spells (Grade 1) by Miranda Goshawk", 
     {"entities": [(0, 35, "OBJETO_MAGICO"), (40, 55, "PERSONAJE")]}),
    ("A History of Magic by Bathilda Bagshot", 
     {"entities": [(0, 19, "OBJETO_MAGICO"), (23, 39, "PERSONAJE")]}),
    ("One Thousand Magical Herbs and Fungi by Phyllida Spore", 
     {"entities": [(0, 36, "OBJETO_MAGICO"), (40, 53, "PERSONAJE")]}),
    ("Fantastic Beasts and Where to Find Them by Newt Scamander", 
     {"entities": [(0, 38, "OBJETO_MAGICO"), (42, 56, "PERSONAJE")]}),
    ("1 wand", 
     {"entities": [(2, 6, "OBJETO_MAGICO")]}),
    ("1 cauldron (pewter, standard size 2)", 
     {"entities": [(2, 11, "OBJETO_MAGICO")]}),
    ("1 set of glass or crystal phials", 
     {"entities": [(28, 34, "OBJETO_MAGICO")]}),
    ("Students may also bring an owl OR a cat OR a toad", 
     {"entities": [(27, 30, "OBJETO_MAGICO"), (35, 38, "PERSONAJE"), (43, 47, "OBJETO_MAGICO")]}),
    ("PARENTS ARE REMINDED THAT FIRST YEARS ARE NOT ALLOWED THEIR OWN BROOMSTICKS", 
     {"entities": [(65, 76, "OBJETO_MAGICO")]}),
    ("...nowhere that looked as if it could sell you a magic wand.", 
     {"entities": [(51, 62, "OBJETO_MAGICO")]}),
    ("Were there really shops that sold spell books and broomsticks?", 
     {"entities": [(34, 45, "OBJETO_MAGICO"), (50, 61, "OBJETO_MAGICO")]}),
    ("“This is it,” said Hagrid, coming to a halt, “the Leaky Cauldron. It’s a famous place.”", 
     {"entities": [(19, 25, "PERSONAJE"), (49, 66, "LUGAR")]}),
    ("“Can’t, Tom, I’m on Hogwarts business,” said Hagrid...", 
     {"entities": [(7, 10, "PERSONAJE"), (18, 26, "LUGAR"), (40, 46, "PERSONAJE")]}),
    ("“Bless my soul,” whispered the old bartender, “Harry Potter…what an honor.”", 
     {"entities": [(45, 57, "PERSONAJE")]}),
    ("“Doris Crockford, Mr. Potter, can’t believe I’m meeting you at last.”", 
     {"entities": [(1, 16, "PERSONAJE"), (18, 27, "PERSONAJE")]}),
    ("“Delighted, Mr. Potter, just can’t tell you, Diggle’s the name, Dedalus Diggle.”", 
     {"entities": [(12, 21, "PERSONAJE"), (50, 65, "PERSONAJE")]}),
    ("“Professor Quirrell!” said Hagrid. “Harry, Professor Quirrell will be one of your teachers at Hogwarts.”", 
     {"entities": [(1, 19, "PERSONAJE"), (27, 33, "PERSONAJE"), (36, 41, "PERSONAJE"), (43, 61, "PERSONAJE"), (89, 97, "LUGAR")]}),
    ("“D-Defense Against the D-D-Dark Arts,” muttered Professor Quirrell...", 
     {"entities": [(47, 65, "PERSONAJE")]}),
    ("They say he met vampires in the Black Forest, and there was a nasty bit o’ trouble with a hag...", 
     {"entities": [(19, 27, "PERSONAJE"), (35, 48, "LUGAR"), (89, 92, "PERSONAJE")]}),
    ("“Welcome,” said Hagrid, “to Diagon Alley.”", 
     {"entities": [(18, 24, "PERSONAJE"), (29, 42, "LUGAR")]}),
    ("“Dragon liver, seventeen Sickles an ounce, they’re mad.…”", 
     {"entities": [(0, 12, "OBJETO_MAGICO"), (23, 30, "OBJETO_MAGICO")]}),
    ("...a sign saying Eeylops Owl Emporium — Tawny, Screech, Barn, Brown, and Snowy.", 
     {"entities": [(16, 37, "LUGAR")]}),
    ("“Look,” Harry heard one of them say, “the new Nimbus Two Thousand — fastest ever —”", 
     {"entities": [(6, 11, "PERSONAJE"), (42, 62, "OBJETO_MAGICO")]}),
    ("...windows stacked with barrels of bat spleens and eels’ eyes, tottering piles of spell books, quills, and rolls of parchment, potion bottles, globes of the moon.…", 
     {"entities": [(34, 45, "OBJETO_MAGICO"), (50, 60, "OBJETO_MAGICO"), (82, 93, "OBJETO_MAGICO"), (95, 101, "OBJETO_MAGICO"), (107, 126, "OBJETO_MAGICO"), (128, 142, "OBJETO_MAGICO"), (144, 161, "OBJETO_MAGICO")]}),
    ("“Yeah, that’s a goblin,” said Hagrid quietly as they walked up the white stone steps toward him.", 
     {"entities": [(15, 21, "PERSONAJE"), (29, 35, "PERSONAJE")]}),
    ("“An’ I’ve also got a letter here from Professor Dumbledore,” said Hagrid importantly...", 
     {"entities": [(40, 59, "PERSONAJE"), (67, 73, "PERSONAJE")]}),
    ("It’s about the You-Know-What in vault seven hundred and thirteen.”", 
     {"entities": [(32, 62, "OBJETO_MAGICO")]}),
    ("I will have someone take you down to both vaults. Griphook!”", 
     {"entities": [(51, 59, "PERSONAJE")]}),
    ("The gold ones are Galleons,” he explained.", 
     {"entities": [(19, 27, "OBJETO_MAGICO")]}),
    ("Seventeen silver Sickles to a Galleon and twenty-nine Knuts to a Sickle...", 
     {"entities": [(18, 25, "OBJETO_MAGICO"), (31, 38, "OBJETO_MAGICO"), (53, 58, "OBJETO_MAGICO"), (64, 70, "OBJETO_MAGICO")]}),
    ("...so Harry entered Madam Malkin’s shop alone, feeling nervous.", 
     {"entities": [(12, 17, "PERSONAJE"), (25, 40, "PERSONAJE")]}),
    ("Harry was strongly reminded of Dudley.", 
     {"entities": [(0, 5, "PERSONAJE"), (31, 37, "PERSONAJE")]}),
    ("“Play Quidditch at all?”", 
     {"entities": [(6, 15, "OBJETO_MAGICO")]}),
    ("...but I know I’ll be in Slytherin, all our family have been — imagine being in Hufflepuff, I think I’d leave, wouldn’t you?”", 
     {"entities": [(28, 37, "CASA_HOGWARTS"), (84, 94, "CASA_HOGWARTS")]}),
    ("...some o’ the best I ever saw were the only ones with magic in ‘em in a long line o’ Muggles — look at yer mum!", 
     {"entities": []}),
    ("They bought Harry’s school books in a shop called Flourish and Blotts where the shelves were stacked to the ceiling with books...", 
     {"entities": [(12, 17, "PERSONAJE"), (49, 68, "LUGAR")]}),
    ("Hagrid almost had to drag Harry away from Curses and Countercurses... by Professor Vindictus Viridian.", 
     {"entities": [(0, 6, "PERSONAJE"), (18, 23, "PERSONAJE"), (31, 56, "OBJETO_MAGICO"), (65, 92, "PERSONAJE")]}),
    ("...silver unicorn horns at twenty-one Galleons each and minuscule, glittery-black beetle eyes (five Knuts a scoop).", 
     {"entities": [(9, 28, "OBJETO_MAGICO"), (43, 51, "OBJETO_MAGICO"), (86, 107, "OBJETO_MAGICO"), (109, 114, "OBJETO_MAGICO")]}),
    ("Just Ollivanders left now — only place fer wands, Ollivanders, and yeh gotta have the best wand.”", 
     {"entities": [(5, 16, "LUGAR"), (43, 48, "OBJETO_MAGICO"), (50, 61, "LUGAR"), (90, 94, "OBJETO_MAGICO")]}),
    ("Peeling gold letters over the door read Ollivanders: Makers of Fine Wands since 382 B.C.", 
     {"entities": [(38, 49, "LUGAR"), (65, 70, "OBJETO_MAGICO")]}),
    ("Mr. Ollivander moved closer to Harry.", 
     {"entities": [(0, 13, "PERSONAJE"), (30, 35, "PERSONAJE")]}),
    ("Every Ollivander wand has a core of a powerful magical substance, Mr. Potter.", 
     {"entities": [(6, 23, "OBJETO_MAGICO"), (70, 79, "PERSONAJE")]}),
    ("We use unicorn hairs, phoenix tail feathers, and the heartstrings of dragons.", 
     {"entities": [(7, 21, "OBJETO_MAGICO"), (23, 43, "OBJETO_MAGICO"), (52, 78, "OBJETO_MAGICO")]}),
    ("I remember every wand I’ve ever sold, Mr. Potter.", 
     {"entities": [(18, 22, "OBJETO_MAGICO"), (41, 50, "PERSONAJE")]}),
    ("It so happens that the phoenix whose tail feather is in your wand, gave another feather — just one other.", 
     {"entities": [(25, 32, "PERSONAJE"), (44, 50, "OBJETO_MAGICO"), (60, 64, "OBJETO_MAGICO")]}),
      ("“Lumos,” said Dumbledore, as he reached the boulder closest to the cliff face.", 
     {"entities": [(1, 6, "HECHIZO"), (14, 24, "PERSONAJE")]}),
    ("“Then take off your Invisibility Cloak — there is no need for it now — and let us take the plunge,”", 
     {"entities": [(21, 39, "OBJETO_MAGICO")]}),
    ("...the passing light of Dumbledore’s wand.", 
     {"entities": [(24, 34, "PERSONAJE"), (35, 39, "OBJETO_MAGICO")]}),
    ("Then he saw Dumbledore rising out of the water ahead, his silver hair and dark robes gleaming.", 
     {"entities": [(13, 23, "PERSONAJE")]}),
    ("Now it is Lord Voldemort’s obstacles that stand in our way, rather than those nature made. . . .", 
     {"entities": [(11, 26, "PERSONAJE")]}),
    ("Harry did not ask how Dumbledore knew.", 
     {"entities": [(0, 5, "PERSONAJE"), (22, 32, "PERSONAJE")]}),
    ("Dumbledore stepped back from the cave wall and pointed his wand at the rock.", 
     {"entities": [(0, 10, "PERSONAJE"), (55, 59, "OBJETO_MAGICO")]}),
    ("“I rather think,” said Dumbledore, putting his uninjured hand inside his robes and drawing out a short silver knife...", 
     {"entities": [(22, 32, "PERSONAJE"), (111, 123, "OBJETO_MAGICO")]}),
    ("“Yes,” said Dumbledore. “Blood, if I am not much mistaken.”", 
     {"entities": [(13, 23, "PERSONAJE"), (26, 31, "OBJETO_MAGICO")]}),
    ("Once again, Lord Voldemort fails to grasp that there are much more terrible things than physical injury.”", 
     {"entities": [(13, 28, "PERSONAJE")]}),
    ("...it healed instantly, just as Snape had healed Malfoy’s wound...", 
     {"entities": [(31, 36, "PERSONAJE"), (49, 55, "PERSONAJE")]}),
    ("An eerie sight met their eyes: They were standing on the edge of a great black lake...", 
     {"entities": [(77, 81, "LUGAR")]}),
    ("“Professor?” he said finally. “Do you think the Horcrux is here?”", 
     {"entities": [(47, 55, "OBJETO_MAGICO")]}),
    ("“Oh yes,” said Dumbledore. “Yes, I’m sure it is.", 
     {"entities": [(10, 20, "PERSONAJE")]}),
    ("But he was much keener than he was prepared to admit on getting out of this place as soon as possible.", 
     {"entities": []}),
    ("Harry had not expected this, but cleared his throat and said loudly, wand aloft, “Accio Horcrux!”", 
     {"entities": [(0, 5, "PERSONAJE"), (70, 74, "OBJETO_MAGICO"), (84, 99, "HECHIZO")]}),
    ("Something, I think, that is ready to respond should we attempt to seize the Horcrux.”", 
     {"entities": [(76, 84, "OBJETO_MAGICO")]}),
    ("I think we must resign ourselves to the fact that they will, at some point, realize we are not Lord Voldemort.", 
     {"entities": [(96, 111, "PERSONAJE")]}),
    ("Voldemort would have been reasonably confident that none but a very great wizard would have been able to find the boat,” said Dumbledore.", 
     {"entities": [(0, 10, "PERSONAJE"), (123, 133, "PERSONAJE")]}),
    ("Voldemort’s mistake, Harry, Voldemort’s mistake. . . Age is foolish and forgetful when it underestimates youth. . . .", 
     {"entities": [(0, 10, "PERSONAJE"), (12, 17, "PERSONAJE"), (19, 29, "PERSONAJE")]}),
    ("Dumbledore stood aside and Harry climbed carefully into the boat.", 
     {"entities": [(0, 10, "PERSONAJE"), (18, 23, "PERSONAJE"), (51, 55, "OBJETO_MAGICO")]}),
    ("There are bodies in here!” said Harry, and his voice sounded much higher than usual and most unlike his own.", 
     {"entities": [(30, 35, "PERSONAJE")]}),
    ("It is the unknown we fear when we look upon death and darkness, nothing more.”", 
     {"entities": []}),
    ("When I tried to Summon the Horcrux, a body leapt out of the lake.”", 
     {"entities": [(16, 32, "OBJETO_MAGICO")]}),
    ("Fire, Harry,” Dumbledore added with a smile, in response to Harry’s bewildered expression.", 
     {"entities": [(7, 12, "PERSONAJE"), (15, 25, "PERSONAJE"), (58, 63, "PERSONAJE")]}),
    ("...he had given Ron and Hermione Felix Felicis. . . .", 
     {"entities": [(17, 20, "PERSONAJE"), (25, 33, "PERSONAJE"), (34, 47, "OBJETO_MAGICO")]}),
    ("The island was no larger than Dumbledore’s office, an expanse of flat dark stone...", 
     {"entities": [(0, 6, "LUGAR"), (30, 40, "PERSONAJE")]}),
    ("...a stone basin rather like the Pensieve, which was set on top of a pedestal.", 
     {"entities": [(10, 15, "OBJETO_MAGICO"), (32, 41, "OBJETO_MAGICO")]}),
    ("This being the case, Harry, it will be your job to make sure I keep drinking...", 
     {"entities": [(22, 27, "PERSONAJE")]}),
    ("“You remember,” said Dumbledore, “the condition on which I brought you with me?”", 
     {"entities": [(20, 30, "PERSONAJE")]}),
    ("“Because I am much older, much cleverer, and much less valuable,” said Dumbledore.", 
     {"entities": [(71, 81, "PERSONAJE")]}),
    ("And he drained the goblet. Harry watched, terrified, his hands gripping the rim of the basin...", 
     {"entities": [(16, 22, "OBJETO_MAGICO"), (24, 29, "PERSONAJE"), (81, 86, "OBJETO_MAGICO")]}),
    ("“No ...” he groaned, as Harry lowered the goblet back into the basin and refilled it for him.", 
     {"entities": [(24, 29, "PERSONAJE"), (38, 44, "OBJETO_MAGICO"), (54, 59, "OBJETO_MAGICO")]}),
    ("...but upon draining the goblet, he sank to his knees, shaking uncontrollably.", 
     {"entities": [(23, 29, "OBJETO_MAGICO")]}),
    ("“Rennervate!” he cried, his wand pointing at Dumbledores chest; there was a flash of red light but nothing happened.", 
     {"entities": [(1, 11, "HECHIZO"), (24, 28, "OBJETO_MAGICO"), (43, 53, "PERSONAJE")]}),
    ("He leapt to his feet and seized the goblet he had dropped in the basin; he barely registered the golden locket lying curled beneath it.", 
     {"entities": [(34, 40, "OBJETO_MAGICO"), (60, 65, "OBJETO_MAGICO"), (90, 103, "OBJETO_MAGICO")]}),
    ("“Aguamenti!” he shouted, jabbing the goblet with his wand.", 
     {"entities": [(1, 11, "HECHIZO"), (39, 45, "OBJETO_MAGICO"), (55, 59, "OBJETO_MAGICO")]}),
    ("A slimy white hand had gripped his wrist, and the creature to whom it belonged was pulling him, slowly, backward across the rock.", 
     {"entities": [(51, 59, "PERSONAJE")]}),
    ("...an army of the dead rising from the black water.", 
     {"entities": []}),
    ("“Petrificus Totalus!” yelled Harry, struggling to cling to the smooth, soaked surface of the island...", 
     {"entities": [(1, 19, "HECHIZO"), (27, 32, "PERSONAJE")]}),
    ("...as he pointed his wand at the Inferius that had his arm.", 
     {"entities": [(23, 27, "OBJETO_MAGICO"), (35, 43, "PERSONAJE")]}),
    ("“Impedimenta! Incarcerous!”", 
     {"entities": [(1, 12, "HECHIZO"), (14, 25, "HECHIZO")]}),
    ("Still slashing at the air with his wand, Harry yelled, “Sectumsempra! SECTUMSEMPRA!”", 
     {"entities": [(34, 38, "OBJETO_MAGICO"), (40, 45, "PERSONAJE"), (54, 66, "HECHIZO"), (68, 81, "HECHIZO")]}),
    ("Dumbledore was on his feet again, pale as any of the surrounding Inferi, but taller than any too, the fire dancing in his eyes; his wand was raised like a torch...", 
     {"entities": [(0, 10, "PERSONAJE"), (65, 71, "PERSONAJE"), (124, 128, "OBJETO_MAGICO")]}),
    ("Dumbledore scooped the locket from the bottom of the stone basin and stowed it inside his robes.", 
     {"entities": [(0, 10, "PERSONAJE"), (22, 28, "OBJETO_MAGICO")]}),
       ("You think the Horcrux is in there, sir?”", 
     {"entities": [(12, 20, "OBJETO_MAGICO")]}),
    ("...and then caught the crystal goblet that he had conjured out of nowhere.", 
     {"entities": [(24, 40, "OBJETO_MAGICO")]}),
     ("Cedric looked down at the Triwizard Cup and then up at Harry.", 
     {"entities": [(0, 6, "PERSONAJE"), (28, 42, "OBJETO_MAGICO"), (55, 60, "PERSONAJE")]}),
     ("The Snitch. His nerveless fingers fumbled for a moment with the pouch at his neck and he pulled it out.",
     {"entities": [(4, 10, "OBJETO_MAGICO")]}),
]

TEST_DATA = [
     ("Don’t you see? Professor McGonagall told me what awful things have happened when wizards have meddled with time …", 
     {"entities": [(18, 38, "PERSONAJE")]}),
    ("‘OK!’ said Harry. ‘It was just an idea, I just thought –’", 
     {"entities": [(11, 16, "PERSONAJE")]}),
    ("But Dumbledore held up his hand to stem the flood of explanations.", 
     {"entities": [(4, 14, "PERSONAJE")]}),
    ("‘Yeah, I saw him,’ said Harry slowly. ‘But … maybe I imagined it … I wasn’t thinking straight … I passed out right afterwards …’", 
     {"entities": [(25, 30, "PERSONAJE")]}),
    ("‘I think –’ Harry swallowed, knowing how strange this was going to sound. ‘I think it was my dad.’", 
     {"entities": [(11, 16, "PERSONAJE")]}),
    ("They saw Lupin, Ron and Pettigrew clambering awkwardly out of the hole in the roots.", 
     {"entities": [(9, 14, "PERSONAJE"), (16, 19, "PERSONAJE"), (24, 33, "PERSONAJE")]}),
    ("Then came Hermione … then the unconscious Snape, drifting weirdly upwards.", 
     {"entities": [(10, 18, "PERSONAJE"), (40, 45, "PERSONAJE")]}),
    ("‘Back to Hagrid’s!’ Harry said. ‘It’s empty now – come on!’", 
     {"entities": [(9, 16, "LUGAR"), (19, 24, "PERSONAJE")]}),
    ("‘What did you do?’ she said fiercely. ‘You said you were only going to keep a lookout!’", 
     {"entities": []}),
    ("He pulled Buckbeak’s rope back over his neck and tied it to the other side of his collar like reins.", 
     {"entities": [(9, 17, "PERSONAJE")]}),
    ("‘He’s there!’ Harry said, spotting Sirius as they rose up beside the window.", 
     {"entities": [(13, 18, "PERSONAJE"), (30, 36, "PERSONAJE")]}),
    ("Cedric looked down at the Triwizard Cup and then up at Harry.", 
     {"entities": [(0, 6, "PERSONAJE"), (28, 42, "OBJETO_MAGICO"), (55, 60, "PERSONAJE")]}),
    ("A hill rose above them to their left. Harry could just make out the outline of a fine old house on the hillside.", 
     {"entities": [(36, 41, "PERSONAJE")]}),
    ("Harry lowered his wand slightly and glanced sideways at Cedric.", 
     {"entities": [(0, 5, "PERSONAJE"), (16, 20, "OBJETO_MAGICO"), (55, 61, "PERSONAJE")]}),
    ("For a second. Harry and Cedric and the short figure simply looked at one another.", 
     {"entities": [(14, 19, "PERSONAJE"), (24, 30, "PERSONAJE")]}),
     ("'You hear him? You hear him? Giving instructions to the other children as though he thinks of fighting us!'",
     {"entities": []}),
    ("But the Death Eaters did not strike.",
     {"entities": [(8, 20, "PERSONAJE")]}),
    ("'I TOLD YOU, NO!' Lucius Malfoy roared at the woman.",
     {"entities": [(18, 32, "PERSONAJE")]}),
    ("He could not think what to do but to keep talking. Neville's arm was pressed against his, and he could feel him shaking;",
     {"entities": [(53, 60, "PERSONAJE")]}),
    ("'You dare speak his name?' whispered Bellatrix.",
     {"entities": [(38, 47, "PERSONAJE")]}),
    ("'Shut your mouth!' Bellatrix shrieked.",
     {"entities": [(18, 27, "PERSONAJE")]}),
    ("'Dumbledore never told you?' Malfoy repeated.",
     {"entities": [(1, 11, "PERSONAJE"), (30, 36, "PERSONAJE")]}),
    ("'Someone made a prophecy about Voldemort and me?' he said quietly, gazing at Lucius Malfoy, his fingers tightening over the warm glass sphere in his hand.",
     {"entities": [(32, 41, "PERSONAJE"), (76, 89, "PERSONAJE")]}),
    ("'Like he tried to get Sturgis to steal it - and Bode?'",
     {"entities": [(23, 30, "PERSONAJE"), (48, 52, "PERSONAJE")]}),
    ("'NOW!' yelled Harry.",
     {"entities": [(14, 19, "PERSONAJE")]}),
    ("‘We did it, Professor!’ Harry whispered with difficulty; he suddenly realised that he had a searing stitch in his chest.",
     {"entities": [(23, 28, "PERSONAJE")]}),
    ("‘I’ve been better,’ said Dumbledore weakly, though the corners of his mouth twitched.",
     {"entities": [(24, 34, "PERSONAJE")]}),
    ("‘No,’ said Dumbledore. ‘It is … Professor Snape whom I need … but I do not think … I can walk very far just yet …’",
     {"entities": [(10, 20, "PERSONAJE"), (30, 44, "PERSONAJE")]}),
    ("'If you help me support him,' said Harry, not listening to her, 'I think we can get him inside -'",
     {"entities": [(35, 40, "PERSONAJE")]}),
    ("And she pointed into the sky, in the direction of Hogwarts.",
     {"entities": [(51, 59, "LUGAR")]}),
    ("‘Must have been minutes ago, it wasn’t there when I put the cat out, but when I got upstairs -’",
     {"entities": []}),
    ("Had Ron, Hermione and Ginny’s luck run out by now?",
     {"entities": [(4, 7, "PERSONAJE"), (9, 17, "PERSONAJE"), (22, 27, "PERSONAJE")]}),
    ("The ramparts were deserted. The door to the spiral staircase that led back into the castle was closed.",
     {"entities": []}),
    ("'You swore to obey me, Harry - go!'",
     {"entities": [(25, 30, "PERSONAJE")]}),
    ("He looked round at Dumbledore, who gestured to him to retreat.",
     {"entities": [(19, 29, "PERSONAJE")]}),
    ("The door burst open and somebody erupted through it and shouted: ‘Expelliarmus!’",
     {"entities": [(64, 77, "HECHIZO")]}),
    ("‘A question 1 might ask you. Or are you acting alone?’",
     {"entities": []}),
    ("They met some of your guard. They’re having a fight down below. They won’t be long … I came on ahead. I - I’ve got a job to do.’",
     {"entities": []}),
    ("‘But why? I don’t think you will kill me, Draco. Killing is not nearly as easy as the innocent believe … so tell me, while we wait for your friends … how did you smuggle them in here?",
     {"entities": [(41, 46, "PERSONAJE")]}),
    ("‘I haven’t got any options!’ said Malfoy, and he was sud denly as white as Dumbledore.",
     {"entities": [(33, 39, "PERSONAJE"), (76, 86, "PERSONAJE")]}),
    ("‘No, Draco,’ said Dumbledore quietly. ‘It is my mercy, and not yours, that matters now.’",
     {"entities": [(5, 10, "PERSONAJE"), (18, 28, "PERSONAJE")]}),
    ("But suddenly footsteps were thundering up the stairs and a second later Malfoy was buffeted out of the way as four people in black robes burst through the door on to the ramparts.",
     {"entities": [(70, 76, "PERSONAJE")]}),
    ("‘Good evening, Amycus,’ said Dumbledore calmly, as though welcoming the man to a tea party.",
     {"entities": [(15, 21, "PERSONAJE"), (29, 39, "PERSONAJE")]}),
    ("‘Is that you, Fenrir?’ asked Dumbledore.",
     {"entities": [(14, 20, "PERSONAJE"), (28, 38, "PERSONAJE")]}),
    ("‘I wouldn’t want to miss a trip to Hogwarts, Dumbledore,’ rasped Greyback.",
     {"entities": [(34, 42, "LUGAR"), (44, 54, "PERSONAJE"), (64, 72, "PERSONAJE")]}),
    ("‘But somebody else had spoken Snape’s name, quite softly.",
     {"entities": [(31, 36, "PERSONAJE")]}),
    ("For the first time, Dumbledore was pleading.",
     {"entities": [(21, 31, "PERSONAJE")]}),
    ("Snape said nothing, but walked forwards and pushed Malfoy roughly out of the way.",
     {"entities": [(0, 5, "PERSONAJE"), (51, 57, "PERSONAJE")]}),
     ("He felt his heart pounding fiercely in his chest. How strange that in his dread of death, it pumped all the harder, valiantly keeping him alive.",
     {"entities": []}),
    ("His will to live had always been so much stronger than his fear of death. Yet it did not occur to him now to try to escape, to outrun Voldemort.",
     {"entities": [(130, 140, "PERSONAJE")]}),
    ("He envied even his parents’ deaths now. This cold-blooded walk to his own destruction would require a different kind of bravery.",
     {"entities": []}),
    ("Slowly, very slowly, he sat up, and as he did so he felt more alive and more aware of his own living body than ever before.",
     {"entities": []}),
    ("But he pulled himself together again: This was crucial, he must be like Dumbledore, keep a cool head, make sure there were backups, others to carry on.",
     {"entities": [(70, 80, "PERSONAJE")]}),
    ("He looked down at the battered gold watch he had received on his seventeenth birthday.",
     {"entities": []}),
    ("“Blimey, Harry, you nearly gave me heart failure!”",
     {"entities": [(8, 13, "PERSONAJE")]}),
    ("But Neville seized his wrist as Harry made to move on.",
     {"entities": [(4, 11, "PERSONAJE"), (30, 35, "PERSONAJE")]}),
    ("“We’re all going to keep fighting, Harry. You know that?”",
     {"entities": [(34, 39, "PERSONAJE")]}),
    ("He wanted to shout out to the night, he wanted Ginny to know that he was there, he wanted her to know where he was going.",
     {"entities": [(47, 52, "PERSONAJE")]}),
    ("He and Voldemort and Snape, the abandoned boys, had all found home here. . . .",
     {"entities": [(7, 17, "PERSONAJE"), (22, 27, "PERSONAJE")]}),
    ("...and his great bearded face, and Ron vomiting slugs, and Hermione helping him save Norbert . . .",
     {"entities": [(35, 38, "PERSONAJE"), (57, 65, "PERSONAJE"), (82, 89, "PERSONAJE")]}),
    ("The Snitch. His nerveless fingers fumbled for a moment with the pouch at his neck and he pulled it out.",
     {"entities": [(4, 10, "OBJETO_MAGICO")]}),
    ("The metal shell broke open. He lowered his shaking hand, raised Draco’s wand beneath the Cloak, and murmured, “Lumos.”",
     {"entities": [(60, 65, "PERSONAJE"), (66, 70, "OBJETO_MAGICO"), (80, 85, "OBJETO_MAGICO"), (101, 107, "HECHIZO")]}),
    ("He closed his eyes and turned the stone over in his hand three times.",
     {"entities": [(31, 36, "OBJETO_MAGICO")]}),
    ("He knew it had happened, because he heard slight movements around him that suggested frail bodies shifting their footing on the earthy, twig-strewn ground that marked the outer edge of the forest.",
     {"entities": [(168, 174, "LUGAR")]}),
    ("Less substantial than living bodies, but much more than ghosts, they moved toward him.",
     {"entities": [(56, 62, "PERSONAJE")]}),
    ("...and his hair was untidy and ruffled, and his glasses were a little lopsided, like Mr. Weasley’s.",
     {"entities": [(85, 96, "PERSONAJE")]}),
    ("Harry looked at his mother.",
     {"entities": [(0, 5, "PERSONAJE")]}),
    ("And he set of. The dementors’ chill did not overcome him; he passed through it with his companions, and they acted like Patronuses to him...",
     {"entities": [(21, 30, "PERSONAJE"), (109, 118, "OBJETO_MAGICO")]}),
    ("He glanced sideways, and his mother smiled at him, and his father nodded encouragement.",
     {"entities": []}),
    ("When Dolohov and Yaxley rejoined the circle, Voldemort looked up.",
     {"entities": [(5, 12, "PERSONAJE"), (17, 23, "PERSONAJE"), (45, 55, "PERSONAJE")]}),
    ("“I thought he would come,” said Voldemort in his high, clear voice, his eyes on the leaping flames.",
     {"entities": [(31, 41, "PERSONAJE")]}),
    ("The giants roared as the Death Eaters rose together, and there were many cries, gasps, even laughter.",
     {"entities": [(4, 10, "PERSONAJE"), (27, 39, "PERSONAJE")]}),
    ("Voldemort had frozen where he stood, but his red eyes had found Harry, and he stared as Harry moved toward him, with nothing but the fire between them.",
     {"entities": [(0, 10, "PERSONAJE"), (66, 71, "PERSONAJE"), (82, 87, "PERSONAJE")]}),
    ("Bellatrix, who had leapt to her feet, was looking eagerly from Voldemort to Harry, her breast heaving.",
     {"entities": [(0, 9, "PERSONAJE"), (63, 73, "PERSONAJE"), (77, 82, "PERSONAJE")]}),
    ("Harry could feel his wand against his chest, but he made no attempt to draw it.",
     {"entities": [(0, 5, "PERSONAJE")]}),
      ("“I dreamed a giant called Hagrid came to tell me I was going to a school for wizards.", 
     {"entities": [(26, 32, "PERSONAJE")]}),
    ("The little bronze ones.”", 
     {"entities": []}),
    ("“Don’t worry about that,” said Hagrid, standing up and scratching his head.", 
     {"entities": [(30, 36, "PERSONAJE")]}),
    ("“Just the one. Gringotts. Run by goblins.”", 
     {"entities": [(15, 24, "LUGAR"), (32, 39, "PERSONAJE")]}),
    ("“Flew,” said Hagrid.", 
     {"entities": [(13, 19, "PERSONAJE")]}),
    ("Hagrid, who didn’t understand “Muggle money,” as he called it, gave the bills to Harry so he could buy their tickets.", 
     {"entities": [(0, 6, "PERSONAJE"), (74, 79, "PERSONAJE")]}),
    ("Magical Drafts and Potions by Arsenius Jigger", 
     {"entities": [(0, 27, "OBJETO_MAGICO"), (31, 46, "PERSONAJE")]}),
    ("The Dark Forces: A Guide to Self-Protection by Quentin Trimble", 
     {"entities": [ (48, 63, "PERSONAJE")]}),
    ("“Can we buy all this in London?” Harry wondered aloud.", 
     {"entities": [(26, 32, "LUGAR"), (35, 40, "PERSONAJE")]}),
    ("If Harry hadn’t known that the Dursleys had no sense of humor, he might have thought so...", 
     {"entities": [(3, 8, "PERSONAJE"), (30, 38, "PERSONAJE")]}),
    ("“The usual, Hagrid?”", 
     {"entities": [(12, 18, "PERSONAJE")]}),
    ("Then he flew off through the open window.", 
     {"entities": []}),
    ("“P-P-Potter,” stammered Professor Quirrell, grasping Harry’s hand, “c-can’t t-tell you how p-pleased I am to meet you.”", 
     {"entities": [(1, 9, "PERSONAJE"), (20, 38, "PERSONAJE"), (49, 54, "PERSONAJE")]}),
    ("“Told yeh, didn’t I? Told yeh you was famous. Even Professor Quirrell was tremblin’ ter meet yeh — mind you, he’s usually tremblin’.”", 
     {"entities": [(50, 68, "PERSONAJE")]}),
    ("He tapped the wall three times with the point of his umbrella.", 
     {"entities": [(53, 61, "OBJETO_MAGICO")]}),
    ("The sun shone brightly on a stack of cauldrons outside the nearest shop.", 
     {"entities": [(36, 45, "OBJETO_MAGICO")]}),
    ("“Gringotts,” said Hagrid.", 
     {"entities": [(1, 10, "LUGAR"), (18, 24, "PERSONAJE")]}),
    ("“Got it,” said Hagrid at last, holding up a tiny golden key.", 
     {"entities": [(15, 21, "PERSONAJE"), (47, 57, "OBJETO_MAGICO")]}),
    ("Once Hagrid had crammed all the dog biscuits back inside his pockets, he and Harry followed Griphook toward one of the doors leading off the hall.", 
     {"entities": [(5, 11, "PERSONAJE"), (71, 76, "PERSONAJE"), (85, 93, "PERSONAJE")]}),
    ("“One speed only,” said Griphook.", 
     {"entities": [(21, 29, "PERSONAJE")]}),
    ("“Better Hufflepuff than Slytherin,” said Hagrid darkly.", 
     {"entities": [(8, 18, "CASA_HOGWARTS"), (24, 33, "CASA_HOGWARTS"), (41, 47, "PERSONAJE")]}),
    ("You-Know-Who was one.”", 
     {"entities": [(0, 12, "PERSONAJE")]}),
    ("Rubeus! Rubeus Hagrid! How nice to see you again.…Oak, sixteen inches, rather bendy, wasn’t it?”", 
     {"entities": [(0, 6, "PERSONAJE"), (8, 22, "PERSONAJE")]}),
    ("No two Ollivander wands are the same, just as no two unicorns, dragons, or phoenixes are quite the same.", 
     {"entities": [(7, 24, "OBJETO_MAGICO"), (60, 68, "PERSONAJE"), (70, 77, "PERSONAJE"), (82, 91, "PERSONAJE")]}),
    ("...holly and phoenix feather, eleven inches, nice and supple.”", 
     {"entities": [(0, 25, "OBJETO_MAGICO")]}),
    ("He paid seven gold Galleons for his wand, and Mr. Ollivander bowed them from his shop.", 
     {"entities": [(21, 29, "OBJETO_MAGICO"), (37, 41, "OBJETO_MAGICO"), (47, 60, "PERSONAJE")]}),
     ("“Not here, precisely,” said Dumbledore.", 
     {"entities": [(28, 38, "PERSONAJE")]}),
    ("No, I think it was only ever Tom Riddle and his youthful victims who visited this spot.", 
     {"entities": [(31, 41, "PERSONAJE")]}),
    ("The lower rocks were slippery with seawater. Harry could feel flecks of cold salt spray hitting his face.", 
     {"entities": [(45, 50, "PERSONAJE")]}),
    ("He continued to swim in Dumbledore’s wake, the tips of his benumbed fingers brushing the rough, wet rock.", 
     {"entities": [(26, 36, "PERSONAJE")]}),
    ("“Yes, this is the place,” said Dumbledore.", 
     {"entities": [(30, 40, "PERSONAJE")]}),
    ("“How can you tell?” Harry spoke in a whisper.", 
     {"entities": [(20, 25, "PERSONAJE")]}),
    ("The entrance is concealed.”", 
     {"entities": []}),
    ("“Thank you,” said Harry gratefully, but Dumbledore had already turned his attention back to the solid cave wall.", 
     {"entities": [(18, 23, "PERSONAJE"), (38, 48, "PERSONAJE")]}),
    ("“Payment?” said Harry. “You’ve got to give the door something?”", 
     {"entities": [(15, 20, "PERSONAJE")]}),
    ("“Professor!” protested Harry, hurrying forward as Dumbledore raised his knife.", 
     {"entities": [(22, 27, "PERSONAJE"), (49, 59, "PERSONAJE"), (71, 76, "OBJETO_MAGICO")]}),
    ("He set off around the edge of the lake, and Harry followed close behind him.", 
     {"entities": [(37, 41, "LUGAR"), (47, 52, "PERSONAJE")]}),
    ("“Certainly we could,” said Dumbledore, stopping so suddenly that Harry almost walked into him.", 
     {"entities": [(27, 37, "PERSONAJE"), (63, 68, "PERSONAJE")]}),
    ("Did you think that would happen, sir?”", 
     {"entities": []}),
    ("“Do you think we’re going to have to go into the lake?”", 
     {"entities": [(51, 55, "LUGAR")]}),
    ("“You don’t think the Horcrux is at the bottom?”", 
     {"entities": [(20, 28, "OBJETO_MAGICO")]}),
    ("I taught Tom Riddle. I know his style.”", 
     {"entities": [(9, 19, "PERSONAJE")]}),
    ("“Is … is this boat safe?”", 
     {"entities": [(15, 19, "OBJETO_MAGICO")]}),
    ("“I do not think you will count, Harry: You are underage and unqualified.", 
     {"entities": [(33, 38, "PERSONAJE")]}),
    ("“Professor!” he said, and his startled voice echoed loudly over the silent water.", 
     {"entities": []}),
    ("“I think I saw a hand in the water — a human hand!”", 
     {"entities": []}),
    ("“Yes, I am sure you did,” said Dumbledore calmly.", 
     {"entities": [(31, 41, "PERSONAJE")]}),
    ("But then, through the darkness, fire erupted: crimson and gold, a ring of fire that surrounded the rock...", 
     {"entities": []}),
    ("The little boat sank into the water once more; clanking and tinkling, its chain slithered back into the lake too.", 
     {"entities": [(78, 83, "OBJETO_MAGICO")]}),
    ("...pulling Dumbledore’s uninjured arm around his shoulders, Harry guided his headmaster back around the lake...", 
     {"entities": [(8, 18, "PERSONAJE"), (55, 60, "PERSONAJE"), (98, 102, "LUGAR")]}),
    ("“I am not worried, Harry,” said Dumbledore, his voice a little stronger despite the freezing water.", 
     {"entities": [(20, 25, "PERSONAJE"), (33, 43, "PERSONAJE")]}),
]


total = len(TRAIN_DATA) + len(TEST_DATA)
train_ratio = len(TRAIN_DATA) / total if total else 0
test_ratio = len(TEST_DATA) / total if total else 0

print("Total data:", total)
print("TRAIN_DATA count:", len(TRAIN_DATA))
print("TEST_DATA count:", len(TEST_DATA))
print(f"Proporción TRAIN_DATA: {train_ratio:.2f} (ideal ~0.80)")
print(f"Proporción TEST_DATA: {test_ratio:.2f} (ideal ~0.20)")
